title: "Spancat datasets"
description: |
  This project compiles various spancat datasets and their converters into the
  [spaCy format](https://spacy.io/api/data-formats).

vars:
  spans_key: "sc"

directories:
  - "assets"
  - "configs"
  - "corpus"
  - "scripts"
  - "training"
  - "metrics"

assets:
  - dest: "assets/sec_filings-train.iob"
    description: "SEC filings training dataset from Alvarado et al. (ALTA 2015)"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/SEC-filings/CONLL-format/data/train/FIN5.txt
  - dest: "assets/sec_filings-test.iob"
    description: "SEC filings test dataset from Alvarado et al. (ALTA 2015)"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/SEC-filings/CONLL-format/data/test/FIN3.txt
  - dest: "assets/wnut17-train.iob"
    description: "WNUT17 training dataset for Emerging and Rare Entities Task from Derczynski et al., 2017"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/WNUT17/CONLL-format/data/train/wnut17train.conll
  - dest: "assets/wnut17-dev.iob"
    description: "WNUT17 dev dataset for Emerging and Rare Entities Task from Derczynski et al., 2017"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/WNUT17/CONLL-format/data/dev/emerging.dev.conll
  - dest: "assets/wnut17-test.iob"
    description: "WNUT17 test dataset for Emerging and Rare Entities Task from Derczynski et al., 2017"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/WNUT17/CONLL-format/data/test/emerging.test.annotated
  - dest: "assets/btc-general.iob"
    description: "Broad Twitter Corpus (BTC) containing UK general tweets from Derczynski et al., 2016"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/BTC/CONLL-format/data/a.conll
  - dest: "assets/anem-train.iob"
    description: "Anatomical Entity Mention (AnEM) training corpus containing abstracts and full-text biomedical papers from Ohta et al. (ACL 2012)"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/AnEM/CONLL-format/data/AnEM.train
  - dest: "assets/anem-test.iob"
    description: "Anatomical Entity Mention (AnEM) test corpus containing abstracts and full-text biomedical papers from Ohta et al. (ACL 2012)"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/AnEM/CONLL-format/data/AnEM.test

commands:
  - name: "install"
    help: "Install dependencies"
    script:
      - "pip install --user -r requirements.txt"

  - name: "convert-sec_filings"
    help: "Convert SEC filings dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/sec_filings-train.iob corpus/
        --spans-key ${vars.spans_key}
        --converter auto
      - >-
        python -m scripts.convert_to_spans
        assets/sec_filings-test.iob corpus/
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - assets/sec_filings-train.iob
      - assets/sec_filings-test.iob
    outputs:
      - corpus/sec_filings-train.spacy
      - corpus/sec_filings-test.spacy

  - name: "convert-wnut17"
    help: "Convert WNUT17 dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/wnut17-train.iob corpus/
        --spans-key ${vars.spans_key}
        --converter auto
      - >-
        python -m scripts.convert_to_spans
        assets/wnut17-dev.iob corpus/
        --spans-key ${vars.spans_key}
        --converter auto
      - >-
        python -m scripts.convert_to_spans
        assets/wnut17-test.iob corpus/
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - assets/wnut17-train.iob
      - assets/wnut17-dev.iob
      - assets/wnut17-test.iob
    outputs:
      - corpus/wnut17-train.spacy
      - corpus/wnut17-dev.spacy
      - corpus/wnut17-test.spacy

  - name: "convert-btc"
    help: "Convert BTC dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/btc-general.iob corpus/
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - assets/btc-general.iob
    outputs:
      - corpus/btc-general.spacy

  - name: "convert-anem"
    help: "Convert AneM dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/anem-train.iob corpus/
        --spans-key ${vars.spans_key}
        --converter auto
      - >-
        python -m scripts.convert_to_spans
        assets/anem-test.iob corpus/
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - assets/anem-train.iob
      - assets/anem-test.iob
    outputs:
      - corpus/anem-train.spacy
      - corpus/anem-test.spacy

  - name: "clean"
    help: "Remove intermediary files"
    script:
      - "rm -rf assets/*"
      - "rm -rf corpus/*"
      - "rm -rf training/*"
      - "rm -rf metrics/*"
