title: "Spancat datasets"
description: |
  This project compiles various spancat datasets and their converters into the
  [spaCy format](https://spacy.io/api/data-formats).

vars:
  spans_key: "sc"
  gpu_id: 1

directories:
  - "assets"
  - "configs"
  - "corpus"
  - "corpus/spancat"
  - "corpus/ner"
  - "scripts"
  - "training"
  - "metrics"

workflows:
  anem:
    - "convert-anem"
    - "train-anem"
    - "evaluate-anem"
  sec-filings:
    - "convert-sec_filings"
    - "train-sec_filings"
    - "evaluate-sec_filings"

assets:
  - dest: "assets/sec_filings-train.iob"
    description: "SEC filings training dataset from Alvarado et al. (ALTA 2015)"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/SEC-filings/CONLL-format/data/train/FIN5.txt
  - dest: "assets/sec_filings-test.iob"
    description: "SEC filings test dataset from Alvarado et al. (ALTA 2015)"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/SEC-filings/CONLL-format/data/test/FIN3.txt
  - dest: "assets/wnut17-train.iob"
    description: "WNUT17 training dataset for Emerging and Rare Entities Task from Derczynski et al., 2017"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/WNUT17/CONLL-format/data/train/wnut17train.conll
  - dest: "assets/wnut17-dev.iob"
    description: "WNUT17 dev dataset for Emerging and Rare Entities Task from Derczynski et al., 2017"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/WNUT17/CONLL-format/data/dev/emerging.dev.conll
  - dest: "assets/wnut17-test.iob"
    description: "WNUT17 test dataset for Emerging and Rare Entities Task from Derczynski et al., 2017"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/WNUT17/CONLL-format/data/test/emerging.test.annotated
  - dest: "assets/btc-general.iob"
    description: "Broad Twitter Corpus (BTC) containing UK general tweets from Derczynski et al., 2016"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/BTC/CONLL-format/data/a.conll
  - dest: "assets/anem-train.iob"
    description: "Anatomical Entity Mention (AnEM) training corpus containing abstracts and full-text biomedical papers from Ohta et al. (ACL 2012)"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/AnEM/CONLL-format/data/AnEM.train
  - dest: "assets/anem-test.iob"
    description: "Anatomical Entity Mention (AnEM) test corpus containing abstracts and full-text biomedical papers from Ohta et al. (ACL 2012)"
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/AnEM/CONLL-format/data/AnEM.test
  - dest: "assets/wikigold.iob"
    description: "Wikigold dataset containing a manually annotated collection of Wikipedia text by Balasuriya et al. (ACL 2009)."
    url: https://github.com/juand-r/entity-recognition-datasets/blob/master/data/wikigold/CONLL-format/data/wikigold.conll.txt
  - dest: "assets/en-wikineural-train.iob"
    description: "WikiNeural (en) training dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/en/train.conllu
  - dest: "assets/en-wikineural-dev.iob"
    description: "WikiNeural (en) dev dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/en/val.conllu
  - dest: "assets/en-wikineural-test.iob"
    description: "WikiNeural (en) test dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/en/test.conllu
  - dest: "assets/de-wikineural-train.iob"
    description: "WikiNeural (de) training dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/de/train.conllu
  - dest: "assets/de-wikineural-dev.iob"
    description: "WikiNeural (de) dev dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/de/val.conllu
  - dest: "assets/de-wikineural-test.iob"
    description: "WikiNeural (de) test dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/de/test.conllu
  - dest: "assets/es-wikineural-train.iob"
    description: "WikiNeural (es) training dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/es/train.conllu
  - dest: "assets/es-wikineural-dev.iob"
    description: "WikiNeural (es) dev dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/es/val.conllu
  - dest: "assets/es-wikineural-test.iob"
    description: "WikiNeural (es) test dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/es/test.conllu
  - dest: "assets/nl-wikineural-train.iob"
    description: "WikiNeural (nl) training dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/nl/train.conllu
  - dest: "assets/nl-wikineural-dev.iob"
    description: "WikiNeural (nl) dev dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/nl/val.conllu
  - dest: "assets/nl-wikineural-test.iob"
    description: "WikiNeural (nl) test dataset from Tedeschi et al. (EMNLP 2021)"
    url: https://github.com/Babelscape/wikineural/blob/master/data/conll/nl/test.conllu

commands:
  - name: "install"
    help: "Install dependencies"
    script:
      - "pip install --user -r requirements.txt"
      - "python -m spacy download en_core_web_lg"

  - name: "convert-sec_filings"
    help: "Convert SEC filings dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/sec_filings-train.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
        --train-size 0.8
        --seed 42
        --shuffle
      - >-
        python -m scripts.convert_to_spans
        assets/sec_filings-test.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      # NER conversion doc.ents
      - >-
        python -m scripts.convert_to_spans
        assets/sec_filings-train.iob corpus/ner/
        --use-ents
        --converter auto
        --train-size 0.8
        --seed 42
        --shuffle
      - >-
        python -m scripts.convert_to_spans
        assets/sec_filings-test.iob corpus/ner/
        --use-ents
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - assets/sec_filings-train.iob
      - assets/sec_filings-test.iob
    outputs:
      - corpus/spancat/sec_filings-train.spacy
      - corpus/spancat/sec_filings-train-dev.spacy
      - corpus/spancat/sec_filings-test.spacy
      - corpus/ner/sec_filings-train-dev.spacy
      - corpus/ner/sec_filings-test.spacy

  - name: "train-sec_filings"
    help: "Train an NER and Spancat model for SEC Filings dataset"
    script:
      - >-
        python -m spacy train
        configs/ner.cfg
        --output training/sec_filings/ner/
        --paths.train corpus/ner/sec_filings-train.spacy
        --paths.dev corpus/ner/sec_filings-train-dev.spacy
        --gpu-id ${vars.gpu_id}
      - >-
        python -m spacy train
        configs/spancat.cfg
        --output training/sec_filings/spancat/
        --paths.train corpus/spancat/sec_filings-train.spacy
        --paths.dev corpus/spancat/sec_filings-train-dev.spacy
        --gpu-id ${vars.gpu_id}
    deps:
      - corpus/spancat/sec_filings-train.spacy
      - corpus/spancat/sec_filings-train-dev.spacy
      - corpus/spancat/sec_filings-test.spacy
      - corpus/ner/sec_filings-train-dev.spacy
      - corpus/ner/sec_filings-test.spacy
    outputs:
      - training/sec_filings/ner/model-best
      - training/sec_filings/spancat/model-best

  - name: "evaluate-sec_filings"
    help: "Evaluate the results for the SEC Filings dataset"
    script:
      - "mkdir -p metrics/sec_filings/spancat"
      - >-
        python -m spacy evaluate
        training/sec_filings/spancat/model-best
        corpus/spancat/sec_filings-test.spacy
        --output metrics/sec_filings/spancat/scores.json
      - "mkdir -p metrics/sec_filings/ner"
      - >-
        python -m spacy evaluate
        training/sec_filings/ner/model-best
        corpus/ner/sec_filings-test.spacy
        --output metrics/sec_filings/ner/scores.json
    deps:
      - training/sec_filings/ner/model-best
      - training/sec_filings/spancat/model-best
      - corpus/ner/sec_filings-test.spacy
      - corpus/spancat/sec_filings-test.spacy
    outputs:
      - metrics/sec_filings/ner/scores.json
      - metrics/sec_filings/spancat/scores.json

  - name: "convert-wnut17"
    help: "Convert WNUT17 dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/wnut17-train.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - >-
        python -m scripts.convert_to_spans
        assets/wnut17-dev.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - >-
        python -m scripts.convert_to_spans
        assets/wnut17-test.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - assets/wnut17-train.iob
      - assets/wnut17-dev.iob
      - assets/wnut17-test.iob
    outputs:
      - corpus/spancat/wnut17-train.spacy
      - corpus/spancat/wnut17-dev.spacy
      - corpus/spancat/wnut17-test.spacy

  - name: "convert-btc"
    help: "Convert BTC dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/btc-general.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - assets/btc-general.iob
    outputs:
      - corpus/spancat/btc-general.spacy

  - name: "convert-anem"
    help: "Convert AneM dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/anem-train.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
        --train-size 0.8
        --seed 42
        --shuffle
      - >-
        python -m scripts.convert_to_spans
        assets/anem-test.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      # NER conversion doc.ents
      - >-
        python -m scripts.convert_to_spans
        assets/anem-train.iob corpus/ner/
        --use-ents
        --converter auto
        --train-size 0.8
        --seed 42
        --shuffle
      - >-
        python -m scripts.convert_to_spans
        assets/anem-test.iob corpus/ner/
        --use-ents
        --converter auto
    deps:
      - assets/anem-train.iob
      - assets/anem-test.iob
    outputs:
      - corpus/ner/anem-train.spacy
      - corpus/ner/anem-train-dev.spacy
      - corpus/ner/anem-test.spacy
      - corpus/spancat/anem-train.spacy
      - corpus/spancat/anem-train-dev.spacy
      - corpus/spancat/anem-test.spacy

  - name: "train-anem"
    help: "Train an NER and Spancat model for AnEM"
    script:
      - >-
        python -m spacy train
        configs/ner.cfg
        --output training/anem/ner/
        --paths.train corpus/ner/anem-train.spacy
        --paths.dev corpus/ner/anem-train-dev.spacy
        --gpu-id ${vars.gpu_id}
      - >-
        python -m spacy train
        configs/spancat.cfg
        --output training/anem/spancat/
        --paths.train corpus/spancat/anem-train.spacy
        --paths.dev corpus/spancat/anem-train-dev.spacy
        --gpu-id ${vars.gpu_id}
    deps:
      - corpus/ner/anem-train.spacy
      - corpus/ner/anem-train-dev.spacy
      - corpus/ner/anem-test.spacy
      - corpus/spancat/anem-train.spacy
      - corpus/spancat/anem-train-dev.spacy
      - corpus/spancat/anem-test.spacy
    outputs:
      - training/anem/ner/model-best
      - training/anem/spancat/model-best

  - name: "evaluate-anem"
    help: "Evaluate AnEM dataset"
    script:
      - "mkdir -p metrics/anem/spancat"
      - >-
        python -m spacy evaluate
        training/anem/spancat/model-best
        corpus/spancat/anem-test.spacy
        --output metrics/anem/spancat/scores.json
      - "mkdir -p metrics/anem/ner"
      - >-
        python -m spacy evaluate
        training/anem/ner/model-best
        corpus/ner/anem-test.spacy
        --output metrics/anem/ner/scores.json
    deps:
      - training/anem/ner/model-best
      - training/anem/spancat/model-best
      - corpus/ner/anem-test.spacy
      - corpus/spancat/anem-test.spacy
    outputs:
      - metrics/anem/ner/scores.json
      - metrics/anem/spancat/scores.json

  - name: "convert-wikigold"
    help: "Convert the Wikigold dataset into the spaCy format"
    script:
      - >-
        python -m scripts.convert_to_spans
        assets/wikigold.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - assets/wikigold.iob
    outputs:
      - corpus/spancat/wikigold.spacy

  - name: "convert-wikineural"
    help: "Convert WikiNeural dataset (de, en, es, nl) into the spaCy format"
    script:
      # Convert de dataset
      - python -m scripts.remove_indices assets/de-wikineural-train.iob
      - >-
        python -m scripts.convert_to_spans
        assets/de-wikineural-train.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - python -m scripts.remove_indices assets/de-wikineural-dev.iob
      - >-
        python -m scripts.convert_to_spans
        assets/de-wikineural-dev.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      # - python -m scripts.remove_indices assets/de-wikineural-test.iob
      # - >-
      #   python -m scripts.convert_to_spans
      #   assets/de-wikineural-test.iob corpus/spancat/
      #   --spans-key ${vars.spans_key}
      #   --converter auto
      # Convert en dataset
      - python -m scripts.remove_indices assets/en-wikineural-train.iob
      - >-
        python -m scripts.convert_to_spans
        assets/en-wikineural-train.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - python -m scripts.remove_indices assets/en-wikineural-dev.iob
      - >-
        python -m scripts.convert_to_spans
        assets/en-wikineural-dev.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - python -m scripts.remove_indices assets/en-wikineural-test.iob
      - >-
        python -m scripts.convert_to_spans
        assets/en-wikineural-test.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      # Convert es dataset
      - python -m scripts.remove_indices assets/es-wikineural-train.iob
      - >-
        python -m scripts.convert_to_spans
        assets/es-wikineural-train.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - python -m scripts.remove_indices assets/es-wikineural-dev.iob
      - >-
        python -m scripts.convert_to_spans
        assets/es-wikineural-dev.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - python -m scripts.remove_indices assets/es-wikineural-test.iob
      - >-
        python -m scripts.convert_to_spans
        assets/es-wikineural-test.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      # Convert nl dataset
      - python -m scripts.remove_indices assets/nl-wikineural-train.iob
      - >-
        python -m scripts.convert_to_spans
        assets/nl-wikineural-train.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - python -m scripts.remove_indices assets/nl-wikineural-dev.iob
      - >-
        python -m scripts.convert_to_spans
        assets/nl-wikineural-dev.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
      - python -m scripts.remove_indices assets/nl-wikineural-test.iob
      - >-
        python -m scripts.convert_to_spans
        assets/nl-wikineural-test.iob corpus/spancat/
        --spans-key ${vars.spans_key}
        --converter auto
    deps:
      - "assets/de-wikineural-train.iob"
      - "assets/de-wikineural-dev.iob"
      # - "assets/de-wikineural-test.iob"
      - "assets/en-wikineural-train.iob"
      - "assets/en-wikineural-dev.iob"
      - "assets/en-wikineural-test.iob"
      - "assets/es-wikineural-train.iob"
      - "assets/es-wikineural-dev.iob"
      - "assets/es-wikineural-test.iob"
      - "assets/nl-wikineural-train.iob"
      - "assets/nl-wikineural-dev.iob"
      - "assets/nl-wikineural-test.iob"
    outputs:
      - "corpus/spancat/de-wikineural-train.spacy"
      - "corpus/spancat/de-wikineural-dev.spacy"
      # - "corpus/spancat/de-wikineural-test.spacy"
      - "corpus/spancat/en-wikineural-train.spacy"
      - "corpus/spancat/en-wikineural-dev.spacy"
      - "corpus/spancat/en-wikineural-test.spacy"
      - "corpus/spancat/es-wikineural-train.spacy"
      - "corpus/spancat/es-wikineural-dev.spacy"
      - "corpus/spancat/es-wikineural-test.spacy"
      - "corpus/spancat/nl-wikineural-train.spacy"
      - "corpus/spancat/nl-wikineural-dev.spacy"
      - "corpus/spancat/nl-wikineural-test.spacy"

  - name: "clean"
    help: "Remove intermediary files"
    script:
      - "rm -rf assets/*"
      - "rm -rf corpus/spancat/*"
      - "rm -rf training/*"
      - "rm -rf metrics/*"
