method: random
metric:
  goal: maximize
  name: ents_f
parameters:
  components.tok2vec.model.embed.attrs:
    values:
      [
        ["NORM", "PREFIX", "SUFFIX", "SHAPE"],
        ["ORTH", "PREFIX", "SUFFIX", "SHAPE"],
        ["NORM", "PREFIX", "SUFFIX"],
        ["ORTH", "PREFIX", "SUFFIX"],
        ["NORM"],
        ["ORTH"],
        ["LOWER"],
      ]
