method: random
metric:
  goal: maximize
  name: ents_f
parameters:
  components.tok2vec.model.embed.attrs:
    values:
      [
        ["NORM", "PREFIX", "SUFFIX", "SHAPE"],
        ["ORTH", "PREFIX", "SUFFIX", "SHAPE"],
        ["NORM", "PREFIX", "SUFFIX"],
        ["ORTH", "PREFIX", "SUFFIX"],
        ["NORM"],
        ["ORTH"],
        ["LOWER"],
      ]
  training.dropout:
    distribution: uniform
    max: 0.5
    min: 0.05
  training.optimizer.learn_rate:
    distribution: uniform
    max: 0.01
    min: 0.001
